---
- name: "Manger folder for VMs and Templates in datacenter"
  community.vmware.vcenter_folder:
    hostname: "{{ vmware_host | mandatory }}"
    username: "{{ vmware_user | mandatory }}"
    password: "{{ vmware_password | mandatory }}"
    validate_certs: "{{ vmware_validate_certs | mandatory }}"
    datacenter: "{{ vmware_datacenter | mandatory }}"
    folder_name: "{{ item['name'] }}"
    parent_folder: "{{ item['parent'] | default(omit, true) }}"
    state: "{{ item['state'] | default(omit, true) }}"
  loop: "{{ vmware_folders }}"
  delegate_to: localhost
