---
- name: "Gather VMware virtual machine disk info"
  community.vmware.vmware_guest_disk_info:
    hostname: "{{ vmware_host | mandatory }}"
    username: "{{ vmware_user | mandatory }}"
    password: "{{ vmware_password | mandatory }}"
    proxy_host: "{{ vmware_proxy_host | default(omit) }}"
    proxy_port: "{{ vmware_proxy_port | default(omit) }}"
    validate_certs: "{{ vmware_validate_certs | mandatory }}"
    datacenter: "{{ vmware_datacenter }}"
    folder: "{{ vmware_folder }}"
    name: "{{ vmware_name }}"
  delegate_to: localhost
  register: vmware_disk
