---
- name: "Manage VMware vCenter folders"
  tags:
    - vmware
    - vmware.folder
  import_tasks: folder.yaml
  when: vmware_folders | length > 0

- name: "Manage VMware network"
  tags:
    - vmware
    - vmware.network
  import_tasks: network.yaml
  when: vmware_networks | selectattr('vlan_id','defined') | length > 0

- name: "Get VMware guest info"
  tags:
    - vmware
    - vmware.guest_info
  import_tasks: guest_info.yaml

- name: "Manage VMware guest"
  tags:
    - vmware
    - vmware.guest
  import_tasks: guest.yaml

- name: "Manage VMware guest custom attributes"
  tags:
    - vmware
    - vmware.guest_custom
  import_tasks: guest_custom.yaml
  when: vmware_guest_custom_attributes | length > 0

- name: "Manage VM Storage Policy"
  tags:
    - vmware
    - vmware.storagepolicy
  import_tasks: storagepolicy.yaml
  when: vmware_storagepolicies['vm_home'] != "" or vmware_storagepolicies['disk'] | length > 0
