---
- name: "Manage VMware vCenter folders"
  tags: vmware.folder
  import_tasks: folder.yml
  when: vmware_folders | length > 0

- name: "Manage VMware network"
  tags: vmware.network
  import_tasks: network.yml
  when: vmware_networks | selectattr('vlan_id','defined') | length > 0

- name: "Manage VMware guest"
  tags: vmware.guest
  import_tasks: guest.yml

- name: "Manage VM Storage Policy"
  tags: vmware.storagepolicy
  import_tasks: storagepolicy.yml
  when: vmware_storagepolicies['vm_home'] != "" or vmware_storagepolicies['disk'] | length > 0
